# Generated by Django 4.1.7 on 2023-02-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_moviereviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieReviews',
        ),
    ]
