# Generated by Django 4.1.7 on 2023-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
