# Generated by Django 4.1.7 on 2023-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_remove_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=5, max_length=(1, 5)),
        ),
    ]
