# Generated by Django 4.1.7 on 2023-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_remove_movie_director_director_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
        migrations.AddField(
            model_name='director',
            name='movie',
            field=models.ManyToManyField(null=True, to='movie_app.movie'),
        ),
    ]
