# Generated by Django 4.1.7 on 2023-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_remove_director_movie_director_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='movie_app.movie'),
        ),
    ]
