# Generated by Django 4.1.7 on 2023-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, related_name='directors', to='movie_app.movie'),
        ),
    ]
