# Generated by Django 4.1.7 on 2023-02-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_alter_director_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='director', to='movie_app.director'),
        ),
    ]
