# Generated by Django 4.1.7 on 2023-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_remove_director_movie_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie', to='movie_app.director'),
        ),
    ]
