# Generated by Django 4.1.7 on 2023-02-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(null=True, related_name='movie', to='movie_app.director'),
        ),
    ]
